app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    fullname = db.Column(db.String(255))
    email = db.Column(db.String(255), unique = True, index = True)
    pass_secure = db.Column(db.String(255))
    marks = db.Column(db.Integer, default = 0)

    def save_user(self):
        '''
        Function to save user object in the database
        '''
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_user_by_email(cls, email):
        '''
        Function to retreive a specific user by email
        '''

        return User.query.filter_by(email = email).first()

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)


    def __repr__(self):
        return f'User {self.fullname}'
class Question:    
    '''
    Country class to define country Objects
    '''

    def __init__(self,id,question,correct_answer,incorrect_answers,answers,all_answers):
        self.id=id
        self.question= question
        self.correct_answer = correct_answer
        self.incorrect_answers = incorrect_answers
        self.answers = answers
        self.all_answers = all_answers

class Leaderboard:
    def __init__(self,id,name,marks):
        self.id=id
        self.name=name
        self.marks=marks

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    # configure UploadSet
    configure_uploads(app,photos)

    # Will add the views and forms

    from .requests import configure_request
    configure_request(app)
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint, send_from_directory
main = Blueprint('main',__name__)
from . import views,errors


def create_app(config_name):
    app = Flask(__name__)
    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from flask_login import login_required, current_user
from .. import db
from ..requests import get_questions
from flask import request
from ..models import User,Leaderboard

@main.route('/')
def index():
    title="Quiz Game"
    return render_template('index.html')

@main.route("/category/<id>")
@login_required
def category(id):
    questions=get_questions(id)
    return render_template("category.html",id=id, questions=questions)

@main.route('/save',methods=['POST'])
def save_marks():
    data=request.json
    user=User.query.filter_by(id = data['id']).first()
    user.marks=data['marks']
    db.session.commit()
    print(user.marks)
    return ''
@main.route('/leaderboard')
def show_users():
    users1=User.query.order_by(User.marks.desc()).all()
    users=[]
    counter=1
    for user in users1:
        new_user = Leaderboard(id=counter,name=user.fullname,marks=user.marks)
        counter=counter+1
        users.append(new_user)
    return render_template("leaderboard.html", users=users)
@main.route('/profile/<uname>')
def profile(uname):

    user = User.get_user_by_email(uname)

    if user is None:
        abort(404)

    return render_template('profile/profile.html', user = user)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {%block styles%}
        {{ super() }}
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Ultra&display=swap" rel="stylesheet">
        <link rel="stylesheet"  type="text/css" href="{{url_for('static', filename = 'css/index.css',v=0.01 )}} ">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poiret+One&display=swap" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script>
            $(document).ready(function(){
                $('#b1').click(function(){
                    $('.rb').show();
                    $('.rb').attr('disabled',true);
                })
            })
            function getanswers(){
                var score=0;
                var counter=0;
                var corranswers=document.getElementsByClassName('corranswer');
                document.getElementById('UserAnswers').innerHTML='';
                var e = document.getElementsByTagName('input');
                let j;
                for(let i=0; i<e.length; i++){
                    if(e[i].type=='radio'){
                        if(e[i].checked){
                            for(j=0;j<corranswers.length;j++){
                                if((corranswers[j].id==e[i].name) && corranswers[j].innerHTML==e[i].value){
                                console.log(corranswers[j].innerHTML);
                                score=score+5;
                                counter+=1
                            }
                            }
                            document.getElementById('UserAnswers').innerHTML+='Q' + e[i].name + '. Your answer was '+ e[i].value +'<br>'+'<br>';
                    }
                }
            }
            document.getElementById('UserAnswers').innerHTML+='You got ' + counter + ' out of 5 correct answers' + '<br>';
            if(counter==5){
                document.getElementById('UserAnswers').innerHTML+='Excellent! You won <br>';
            }
            else if(counter<5 && counter>3){
                document.getElementById('UserAnswers').innerHTML+='Good job! <br>';
            }
            else{
                document.getElementById('UserAnswers').innerHTML+='You need to revise more!<br>';
            }
            var grade= document.getElementsByClassName('usersmarks')[0];
            var rank=parseInt(grade.innerHTML) + score
            document.getElementsByClassName('usersmarks')[0].innerHTML=rank;
            async function postData(url = '', data = {}) {
            const response = await fetch(url, {
                method: 'POST',
                mode: 'cors',
                cache: 'no-cache',
                credentials: 'same-origin',
                headers: {
                'Content-Type': 'application/json'
                },
                redirect: 'follow',
                referrerPolicy: 'no-referrer',
                body: JSON.stringify(data) 
            });
            return response.json();
            }
            postData('http://d-quiz-game.herokuapp.com/save',{marks:rank,id:'{{current_user.id}}'})
            }
        </script>
        <style>
        header,h3{
            font-family: 'Poiret One', cursive;
            font-weight:bolder;
            color: black;
        }
        #nav{
            background-color: rgba(4, 1, 22, 0.966);
            font-family: 'Poiret One', cursive;
            font-weight:bolder;
            color:white;
        }
        footer{
        background-color: rgba(4, 1, 22, 0.966);
        padding: 1%;
        font-family: 'Poiret One', cursive;
        color: white;
        }
        .btn{
            background-color: rgba(4, 1, 22, 0.966);
        }
        a{
            color:white;
        }
        img{
            border-radius: 100%;
        }
        body{
            font-weight: bold;
            background-color:lightgrey;
            background-image:linear-gradient(to right, rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url('../static/qq.jpg');
            background-size:cover;
            background-repeat:no-repeat;
            color: white;
            background-position: fixed;
        }
        </style>
        {% endblock %}
    </head>
    <body>
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock %}
        {% block content %}
        {% endblock%}
        <div class="footer">
            <footer class="text-center" >Copyright 2020 |Quiz-App</footer>
        </div>
    </body>
</html>

app/templates/category.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {%block styles%}
        {{ super() }}
        <style>
            h2{
            font-family: 'Poiret One', cursive;
            font-weight: bolder;
            font-size: 2.5em;
            text-decoration: underline;
            }
        </style>
        {% endblock %}
    </head>
    <body>
        {% block content %}
        <div class='container'>
            <h2 class='text-center'> Questions</h2><br>
        <div class='row'>{{ macro.displayQuestions(questions)}}
            <div class='col-md-4'>
                <b>Current score : <span class='usersmarks' id='{{current_user.marks}}'>{{current_user.marks}}</span></b>
            </div>
        </div>
        <input type='submit' id='b1' class='btn' style='color:white;' onclick='getanswers()'><br><br>
        <b id='UserAnswers' style='color: white;'></b><br><br>
        </div>
        {% endblock%}
    </body> 
</html>

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import 'bootstrap/wtf.html' as wtf %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {%block styles%}
        {{ super() }}
        <style>
          body{
            font-weight: bold;
            background-image:none;
            height: 100vh;
            }
            h2{
            font-family: 'Poiret One', cursive;
            font-weight: bolder;
            font-size: 2.5em;
            text-decoration: underline;
            }
        </style>
        {% endblock %}
    </head>
    <body>
      {% block content %}
      <div class="container-fluid">
        <header class="text-center">
          <h1>Welcome To The Ultimate Quiz App</h1>
          <cite>
            "Education without application is just entertainment".
            <p class="blockquote-footer">_Tim Sanders</p>
          </cite>
          <p>Ready to put your skills to test? Get your Trivia on!</p>
        </header>
        <div class="row">
          <div class="col-sm-6">
                <!-- card one -->
            <div class="panel panel-default" class="card ">
              <div class="panel-heading">
                <h3 class="card-title">Books & Literature</h3><hr>
                <img src="../static/2.jpg" width = 200 height= 200 alt="books"><p class="card-text">This is the Literature trivia category.</p>
                <a href="{{url_for('main.category',id=10)}}" class="btn btn-sm">Quiz me!</a>
              </div>
            </div>
            <!-- card two -->
            <div class="panel panel-default" class="card">
              <div class="panel-heading">
                <h3 class="card-title"> Films </h3><hr>
                <img src="../static/film.jpg" width = 200 height= 200 alt="books"><p class="card-text">This is the Films trivia category.</p>
                <a href="{{url_for('main.category',id=11)}}" class="btn btn-sm">Quiz me!</a>
              </div>
            </div>
            <!-- card three -->
            <div class="panel panel-default" class="card">
              <div class="panel-heading">
                <h3 class="card-title">Music </h3> <hr>
                <img src="../static/ic.jpg" width = 200 height= 200 alt="books"><p class="card-text">This is the Music trivia category.</p>
                <a href="{{url_for('main.category',id=12)}}" class="btn btn-sm">Quiz me!</a>
              </div>
            </div>
            <!-- card four -->
            <div class="panel panel-default" class="card">
              <div class="panel-heading">
                <h3 class="card-title">Television shows</h3> <hr>
                <img src="../static/flix.jpg" width = 200 height= 200 alt="books"><p class="card-text">This is the Tv shows trivia category.</p>
                <a href="{{url_for('main.category',id=14)}}" id="one" class="btn btn-sm">Quiz me!</a>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <!-- card five -->
            <div class="panel panel-default" class="card">
              <div class="panel-heading">
                <h3 class="card-title">Sports</h3> <hr>
                <img src="../static/sports.jpg" width = 200 height= 200 alt="books"><p class="card-text">This is the Sports trivia category.</p>
                <a href="{{url_for('main.category',id=21)}}" id="one" class="btn btn-sm">Quiz me!</a>
              </div>
            </div>
            <!-- card six -->
            <div class="panel panel-default" class="card">
              <div class="panel-heading">
                <h3 class="card-title">Science & Nature</h3> <hr>
                <img src="../static/sce.jpg" width = 200 height= 200 alt="books"><p class="card-text">This is the Science trivia category.</p>
                <a href="{{url_for('main.category',id=17)}}" id="one" class="btn btn-sm">Quiz me!</a>
              </div>
            </div>
            <!-- card seven -->
            <div class="panel panel-default" class="card">
              <div class="panel-heading">
                <h3 class="card-title">History</h3> <hr>
                <img src="../static/hist.jpg" width = 200 height= 200 alt="books"><p class="card-text">This is the History trivia category.</p>
                <a href="{{url_for('main.category',id=23)}}" id="one" class="btn btn-sm">Quiz me!</a>
              </div>
            </div>
            <!-- card eight -->
            <div class="panel panel-default" class="card">
              <div class="panel-heading">
                <h3 class="card-title">Geography</h3> <hr>
                <img src="../static/geo.jpg" width = 200 height= 200 alt="books"><p class="card-text">This is the Geography trivia category.</p>
                <a href="{{url_for('main.category',id=22)}}" id="one" class="btn btn-sm">Quiz me!</a>
              </div>
            </div>
          </div>
        </div>
        <div class="footer">
          <footer class="text-center" >Copyright 2020 | Quiz-App</footer>
        </div>
      </div>
      {% endblock %}
    </body> 
</html>

app/templates/leaderboard.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {%block styles%}
        {{ super() }}
        <style>
            body{
                background-image:linear-gradient(to right, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('../static/qq.jpg');
                background-size:cover;
                background-repeat:no-repeat;
                color: white;
            }
            h2{
            font-family: 'Poiret One', cursive;
            font-weight: bolder;
            font-size: 2.5em;
            text-decoration: underline;
            }
            body{
                height: 100vh;
            }
        </style>
        {% endblock %}
    </head>
    <body>
        {% block content %}
        <div class='container'>
            <h2 class='text-center'> Leaderboard</h2><br>
            <div class='row'>{{ macro.displayUsers(users)}}</div>
        </div>
        {% endblock%}
    </body> 
</html>

app/templates/macros.html
{% macro displayQuestions(questions) %}
    {% for question in questions %}
    <div class='col-md-8'>
        <div>
            <table>
                <tr>
                    <td>{{ question.question}}</td>
                </tr>
                {% for ans in question.all_answers%}
                <tr>
                    <td><input type='radio' class='rb' name='{{question.id}}' value='{{ans}}'/>{{ans}}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td><span class='rb' style='display:none;color:blue;'>The correct answer is <b><label class='corranswer' id='{{question.id}}' >{{question.correct_answer}}</label></b></span></td>
                </tr>
            </table>
            
        </div><br>
    </div>
    {% endfor %}
{% endmacro %}

{% macro displayUsers(users) %}
    {% for user in users %}
    <span>{{user.id}}. </span>
        <span>{{ user.name| capitalize}}</span>
        <span>{{user.marks}}</span><br>
    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation" id='nav'>
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">QUIZ GAME</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{url_for('main.show_users')}}">Leaderboard</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li style="color: white; padding: 15px;"> {{current_user.fullname}} </li>
                <li><a href="{{url_for('main.profile', uname = current_user.email)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign Out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html' %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {%block styles%}
        {{ super() }}
        <style>
            h1{
            font-family: 'Poiret One', cursive;
            font-weight: bolder;
            font-size: 2.5em;
            text-decoration: underline;
            }
            body{
            font-weight: bold;
            background-image:linear-gradient(to right, rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url('../../static/qq.jpg');
            background-size:cover;
            background-repeat:no-repeat;
            color: white;
            background-position: fixed;
            height: 100vh;
            text-align: center;
        }
        </style>
        {% endblock %}
    </head>
    <body>
    {% block content %}
        <h1>Profile Page</h1>
        <p>{{ user.fullname}}, you have <strong>{{ user.marks }}</strong> marks</p>
    {% endblock %}
    </body> 
</html>